apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kisa-ready-service
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16
spec:
  tls:
    - hosts:
        - api.ready.example.com
        - admin.ready.internal
      secretName: ready-service-tls
  rules:
    - host: api.ready.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kisa-ready-service
                port:
                  number: 3000
    - host: admin.ready.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kisa-ready-service
                port:
                  number: 3000
